### Signup ###

POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username":"testuser3d2d4",
    "email":"testuser5@example.com",
    "password":"pssdarD32"
}

### Login ###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "testuser@example.com",
  "password": "Password123!"
}

### Refresh

POST http://localhost:5000/api/auth/refresh
Content-Type: application/json

{
  "email": "testuser@example.com",
  "password": "Password123!"
}